# -*- coding: utf-8 -*-
"""
Master data for the Dream Bookcase:
- title: str
- year: int (BCE as negative)
- themes: List[str]
- O, T, E scores: 1–5
"""

WORKS = [
    # Volume I: Science vs Religion
    {"title": "Dialogue Concerning the Two Chief World Systems", "year": 1632,
     "themes": ["Scientific Method", "Heliocentrism"], "O":5, "T":2, "E":5},
    {"title": "On the Nature of Things", "year": -50,
     "themes": ["Atomism", "Materialism"], "O":5, "T":1, "E":4},
    {"title": "Dialogues Concerning Natural Religion", "year": 1779,
     "themes": ["Skepticism", "Teleology"], "O":2, "T":2, "E":5},
    {"title": "The Age of Reason", "year": 1794,
     "themes": ["Deism", "Scripture Critique"], "O":3, "T":4, "E":5},
    {"title": "On the Origin of Species", "year": 1859,
     "themes": ["Evolution", "Naturalism"], "O":5, "T":1, "E":5},
    {"title": "Why I Am Not a Christian", "year": 1927,
     "themes": ["Atheism", "Logic"], "O":4, "T":3, "E":5},
    {"title": "The God Delusion", "year": 2006,
     "themes": ["Atheism", "Science Advocacy"], "O":5, "T":4, "E":5},
    {"title": "God Is Not Great", "year": 2007,
     "themes": ["Atheism", "Historical Critique"], "O":5, "T":4, "E":5},
    {"title": "The End of Faith", "year": 2004,
     "themes": ["Religious Critique", "Ethics"], "O":3, "T":4, "E":5},
    {"title": "Breaking the Spell", "year": 2006,
     "themes": ["Religion as Phenomenon", "Scientific Study of Faith"], "O":3, "T":3, "E":5},

    # Volume II: Debunking Pseudoscience
    {"title": "The Demon-Haunted World", "year": 1995,
     "themes": ["Scientific Skepticism", "Critical Thinking"], "O":5, "T":3, "E":5},
    {"title": "Fads and Fallacies in the Name of Science", "year": 1957,
     "themes": ["Pseudoscience", "Debunking"], "O":1, "T":2, "E":5},
    {"title": "Why People Believe Weird Things", "year": 1997,
     "themes": ["Psychology of Belief", "Conspiracy"], "O":2, "T":3, "E":5},
    {"title": "Flim-Flam!", "year": 1982,
     "themes": ["Paranormal Debunking", "Illusion"], "O":1, "T":3, "E":5},
    {"title": "Bad Science", "year": 2008,
     "themes": ["Medical Skepticism", "Statistics"], "O":2, "T":3, "E":5},
    {"title": "The Mismeasure of Man", "year": 1981,
     "themes": ["Scientific Racism", "IQ Critique"], "O":2, "T":3, "E":5},
    {"title": "Voodoo Science", "year": 2000,
     "themes": ["Pseudoscientific Claims", "Media"], "O":1, "T":3, "E":5},
    {"title": "Trick or Treatment", "year": 2008,
     "themes": ["Alternative Medicine", "Systematic Review"], "O":2, "T":3, "E":5},
    {"title": "Believing in Magic", "year": 1997,
     "themes": ["Superstition", "Psychology"], "O":2, "T":3, "E":5},
    {"title": "Extraordinary Popular Delusions and the Madness of Crowds", "year": 1841,
     "themes": ["Mass Hysteria", "Economic Bubbles"], "O":1, "T":2, "E":5},

    # Volume III: Logic & Cognitive Bias
    {"title": "Novum Organum", "year": 1620,
     "themes": ["Induction", "Cognitive Bias"], "O":4, "T":5, "E":4},
    {"title": "Discourse on Method", "year": 1637,
     "themes": ["Deduction", "Rationalism"], "O":5, "T":4, "E":5},
    {"title": "An Enquiry Concerning Human Understanding", "year": 1748,
     "themes": ["Empiricism", "Problem of Induction"], "O":2, "T":2, "E":5},
    {"title": "Straight and Crooked Thinking", "year": 1930,
     "themes": ["Logical Fallacies", "Critical Thinking"], "O":1, "T":3, "E":5},
    {"title": "Thinking, Fast and Slow", "year": 2011,
     "themes": ["Cognitive Bias", "Decision Making"], "O":1, "T":3, "E":5},
    {"title": "Predictably Irrational", "year": 2008,
     "themes": ["Behavioral Economics", "Heuristics"], "O":2, "T":4, "E":5},
    {"title": "How We Know What Isn’t So", "year": 1991,
     "themes": ["Reasoning Errors", "Psychology"], "O":2, "T":3, "E":5},
    {"title": "The Art of Thinking Clearly", "year": 2013,
     "themes": ["Cognitive Biases", "Popular Psychology"], "O":1, "T":3, "E":5},
    {"title": "Irrationality", "year": 1992,
     "themes": ["Behavioral Flaws", "Decision Making"], "O":1, "T":3, "E":5},
    {"title": "Influence: The Psychology of Persuasion", "year": 1984,
     "themes": ["Compliance", "Behavioral Science"], "O":1, "T":3, "E":5},
    {"title": "Thinking to Some Purpose", "year": 1939,
     "themes": ["Fallacies", "Logic"], "O":1, "T":3, "E":5},

    # Volume IV: Enlightenment & Humanism
    {"title": "Leviathan", "year": 1651,
     "themes": ["Social Contract", "Materialism"], "O":5, "T":4, "E":4},
    {"title": "Two Treatises of Government", "year": 1689,
     "themes": ["Natural Rights", "Consent"], "O":3, "T":5, "E":4},
    {"title": "Candide", "year": 1759,
     "themes": ["Satire", "Optimism Critique"], "O":1, "T":2, "E":4},
    {"title": "What Is Enlightenment?", "year": 1784,
     "themes": ["Public Reason", "Autonomy"], "O":2, "T":5, "E":5},
    {"title": "A Vindication of the Rights of Woman", "year": 1792,
     "themes": ["Feminism", "Education"], "O":3, "T":5, "E":4},
    {"title": "On Liberty", "year": 1859,
     "themes": ["Freedom of Speech", "Harm Principle"], "O":2, "T":5, "E":5},
    {"title": "Enlightenment Now", "year": 2018,
     "themes": ["Progress", "Data-driven"], "O":2, "T":5, "E":5},
    {"title": "System of Nature", "year": 1770,
     "themes": ["Atheism", "Materialism"], "O":5, "T":4, "E":4},
    {"title": "Common Sense", "year": 1776,
     "themes": ["Political Pamphlet", "Revolution"], "O":3, "T":5, "E":4},
    {"title": "The Federalist Papers", "year": 1788,
     "themes": ["Constitutional Theory", "Republicanism"], "O":3, "T":5, "E":4},
    {"title": "Rights of Man", "year": 1791,
     "themes": ["Revolutionary Politics", "Human Rights"], "O":3, "T":5, "E":4},
    {"title": "Declaration of the Rights of Man and of the Citizen", "year": 1789,
     "themes": ["Natural Rights", "Law"], "O":3, "T":5, "E":4},
    {"title": "United States Declaration of Independence", "year": 1776,
     "themes": ["Natural Rights", "Self-Government"], "O":3, "T":5, "E":4},
    {"title": "The Descent of Man", "year": 1871,
     "themes": ["Evolutionary Theory", "Human Nature"], "O":5, "T":2, "E":5},
    {"title": "The Second Sex", "year": 1949,
     "themes": ["Feminist Theory", "Existentialism"], "O":3, "T":5, "E":4},
    {"title": "The Better Angels of Our Nature", "year": 2011,
     "themes": ["Violence Decline", "Historical Trends"], "O":2, "T":5, "E":5},

    # Volume V: Science Philosophy & Demarcation
    {"title": "The Logic of Scientific Discovery", "year": 1934,
     "themes": ["Falsifiability", "Demarcation"], "O":3, "T":3, "E":5},
    {"title": "The Structure of Scientific Revolutions", "year": 1962,
     "themes": ["Paradigm Shift", "Sociology of Science"], "O":3, "T":3, "E":5},
    {"title": "Against Method", "year": 1975,
     "themes": ["Epistemological Anarchism"], "O":2, "T":2, "E":4},
    {"title": "Defending Science—Within Reason", "year": 2003,
     "themes": ["Philosophy of Science"], "O":3, "T":3, "E":5},
    {"title": "Nonsense on Stilts", "year": 2010,
     "themes": ["Pseudoscience Critique"], "O":2, "T":3, "E":5},

    # Volume VI: Political Delusion & Ideology
    {"title": "1984", "year": 1949,
     "themes": ["Totalitarianism", "Propaganda"], "O":2, "T":2, "E":5},
    {"title": "Animal Farm", "year": 1945,
     "themes": ["Political Allegory", "Revolution"], "O":1, "T":2, "E":5},
    {"title": "The Open Society and Its Enemies", "year": 1945,
     "themes": ["Liberal Democracy", "Critique of Totalitarianism"], "O":3, "T":4, "E":5},
    {"title": "The True Believer", "year": 1951,
     "themes": ["Mass Movements", "Fanaticism"], "O":1, "T":4, "E":5},
    {"title": "Manufacturing Consent", "year": 1988,
     "themes": ["Media Bias", "Propaganda Model"], "O":2, "T":3, "E":5},
    {"title": "The Paranoid Style in American Politics", "year": 1964,
     "themes": ["Conspiracy", "Political Psychology"], "O":1, "T":2, "E":5},

    # Volume VII: Economic Myths & Misperceptions
    {"title": "That Which is Seen, and That Which is Not Seen", "year": 1850,
     "themes": ["Opportunity Cost", "Economic Fallacies"], "O":3, "T":4, "E":4},
    {"title": "Economics in One Lesson", "year": 1946,
     "themes": ["Free Market", "Fallacies"], "O":3, "T":4, "E":4},
    {"title": "The Great Crash 1929", "year": 1955,
     "themes": ["Market Bubbles", "Financial History"], "O":2, "T":3, "E":5},
    {"title": "The Black Swan", "year": 2007,
     "themes": ["Uncertainty", "Probability"], "O":3, "T":3, "E":5},
    {"title": "Misbehaving", "year": 2015,
     "themes": ["Behavioral Economics"], "O":2, "T":3, "E":5},

    # Volume VIII: Conspiracy Thinking & Pathologies
    {"title": "A Culture of Conspiracy", "year": 2003,
     "themes": ["Conspiracy Theory", "Cultural Studies"], "O":1, "T":3, "E":5},
    {"title": "Conspiracy Theories: Causes and Cures", "year": 2008,
     "themes": ["Debunking", "Psychology"], "O":1, "T":3, "E":5},
    {"title": "Post-Truth", "year": 2018,
     "themes": ["Epistemic Crisis", "Media"], "O":1, "T":3, "E":5},
    {"title": "The Righteous Mind", "year": 2012,
     "themes": ["Moral Psychology", "Tribalism"], "O":2, "T":3, "E":5},

    # Volume IX: Pedagogy of Critical Thinking
    {"title": "How We Think", "year": 1910,
     "themes": ["Educational Psychology"], "O":1, "T":3, "E":5},
    {"title": "Teaching as a Subversive Activity", "year": 1969,
     "themes": ["Critical Pedagogy"], "O":1, "T":3, "E":5},
    {"title": "An Experiment in the Development of Critical Thinking", "year": 1941,
     "themes": ["Critical Thinking Development"], "O":1, "T":3, "E":5},
    {"title": "Forms of Intellectual and Ethical Development in the College Years", "year": 1970,
     "themes": ["Educational Development"], "O":1, "T":3, "E":5},
    {"title": "The Miniature Guide to Critical Thinking", "year": 2006,
     "themes": ["Critical Thinking"], "O":1, "T":3, "E":5},
    {"title": "Critical Thinking", "year": 2021,
     "themes": ["Introductory Guide"], "O":1, "T":3, "E":5},
    {"title": "Five Minds for the Future", "year": 2008,
     "themes": ["Future Skills"], "O":1, "T":3, "E":5},
    {"title": "Thinking in Education", "year": 1991,
     "themes": ["Educational Philosophy"], "O":1, "T":3, "E":5},
    {"title": "Learning to Think Things Through", "year": 2012,
     "themes": ["Critical Reasoning"], "O":1, "T":3, "E":5},
    {"title": "Why Don’t Students Like School?", "year": 2009,
     "themes": ["Cognitive Science in Education"], "O":1, "T":3, "E":5},

    # Volume X: Fiction & Satire in Defense of Reason
    {"title": "Gulliver’s Travels", "year": 1726,
     "themes": ["Satire", "Social Critique"], "O":1, "T":2, "E":5},
    {"title": "Brave New World", "year": 1932,
     "themes": ["Dystopia", "Technology"], "O":1, "T":2, "E":5},
    {"title": "Cat’s Cradle", "year": 1963,
     "themes": ["Science Fiction", "Satire"], "O":1, "T":2, "E":5},
    {"title": "Galileo", "year": 1943,
     "themes": ["Scientific Courage", "Drama"], "O":1, "T":2, "E":5},
    {"title": "Foucault’s Pendulum", "year": 1988,
     "themes": ["Conspiracy", "Metafiction"], "O":1, "T":2, "E":5},
    {"title": "Memoirs Found in a Bathtub", "year": 1969,
     "themes": ["Espionage Satire", "Absurdism"], "O":1, "T":2, "E":5},
    {"title": "Blindness", "year": 1995,
     "themes": ["Allegory", "Human Condition"], "O":1, "T":2, "E":5},
    {"title": "Letters from the Earth", "year": 1962,
     "themes": ["Religious Satire"], "O":1, "T":2, "E":5},

    # Volume XI: Global Rationalist Voices
    {"title": "Materialist Aphorisms", "year": -200,
     "themes": ["Materialism", "Atheism"], "O":5, "T":5, "E":3},
    {"title": "Mūlamadhyamakakārikā", "year": 200,
     "themes": ["Buddhist Logic", "Emptiness"], "O":2, "T":2, "E":5},
    {"title": "Materialist Aphorisms", "year": -200,
     "themes": ["Materialism", "Atheism"], "O":5, "T":5, "E":3},
    {"title": "On the Rights of Moors in Europe", "year": 1729,
     "themes": ["Equality", "Enlightenment"], "O":2, "T":4, "E":5},
    {"title": "Why Religion? Why God?", "year": 1937,
     "themes": ["Anti-Superstition", "Secularism"], "O":3, "T":5, "E":4},
    {"title": "The First and Last Freedom", "year": 1954,
     "themes": ["Spiritual Skepticism", "Authority Critique"], "O":2, "T":4, "E":4},
    {"title": "Mozi", "year": -450,
     "themes": ["Utilitarian Ethics", "Anti-Superstition"], "O":3, "T":4, "E":3},
    {"title": "Lunheng", "year": 80,
     "themes": ["Empirical Skepticism", "Critique of Omens"], "O":3, "T":4, "E":4},
    {"title": "The Chinese Renaissance", "year": 1930,
     "themes": ["Pragmatism", "Education Reform"], "O":2, "T":4, "E":4},
    {"title": "New Citizen Essays", "year": 1902,
     "themes": ["Modernization", "Constitutionalism"], "O":2, "T":4, "E":4},
    {"title": "An Encouragement of Learning", "year": 1872,
     "themes": ["Westernization", "Rational Progress"], "O":3, "T":4, "E":4},
    {"title": "Treatises on Astronomy and Calendars", "year": 1800,
     "themes": ["Empirical Astronomy", "Calendar Reform"], "O":5, "T":3, "E":4},
    {"title": "The Box Man", "year": 1973,
     "themes": ["Existentialism", "Identity"], "O":1, "T":2, "E":4},
    {"title": "The Face of Another", "year": 1964,
     "themes": ["Perception", "Selfhood"], "O":1, "T":2, "E":4},
    {"title": "Book of Optics", "year": 1021,
     "themes": ["Experimental Science", "Optics"], "O":5, "T":4, "E":5},
    {"title": "Theological-Political Treatise", "year": 1670,
     "themes": ["Free Thought", "Secularism"], "O":4, "T":5, "E":4},
    {"title": "Annihilation of Caste", "year": 1936,
     "themes": ["Social Reform", "Equality"], "O":4, "T":5, "E":4},
    {"title": "Muqaddimah", "year": 1377,
     "themes": ["Historiography", "Sociology"], "O":4, "T":3, "E":5},
    {"title": "The African Origin of Civilization", "year": 1974,
     "themes": ["Historical Revisionism", "Anthropology"], "O":3, "T":4, "E":5},
    {"title": "The Open Sore of a Continent", "year": 1996,
     "themes": ["Political Critique", "Postcolonialism"], "O":2, "T":4, "E":4},
    {"title": "Decolonising the Mind", "year": 1986,
     "themes": ["Language", "Cultural Critique"], "O":2, "T":5, "E":5},
    {"title": "On the Causes of Heat and Cold", "year": 1743,
     "themes": ["Physics", "Natural Philosophy"], "O":5, "T":3, "E":4},
    {"title": "My Past and Thoughts", "year": 1860,
     "themes": ["Autobiography", "Political Thought"], "O":2, "T":4, "E":4},
    {"title": "Memoirs", "year": 1990,
     "themes": ["Human Rights", "Scientific Humanism"], "O":4, "T":5, "E":4},
    {"title": "Life and Fate", "year": 1960,
     "themes": ["Totalitarianism", "Moral Clarity"], "O":2, "T":2, "E":5},
    {"title": "Thought and Language", "year": 1934,
     "themes": ["Developmental Psychology", "Education"], "O":2, "T":3, "E":5},
    {"title": "Hayy ibn Yaqzan", "year": 1180,
     "themes": ["Philosophical Novel", "Reason vs Revelation"], "O":3, "T":3, "E":4},
    {"title": "The Story of Mr. Wang", "year": 1919,
     "themes": ["Superstition", "Cultural Critique"], "O":1, "T":2, "E":4},
    {"title": "The Story of an African Farm", "year": 1883,
     "themes": ["Colonial Critique", "Feminism"], "O":2, "T":3, "E":4},
    {"title": "Letter from Birmingham Jail", "year": 1963,
     "themes": ["Civil Rights", "Justice"], "O":2, "T":5, "E":5},
]
